# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: download-and-save-most-frequent
  annotations:
    tekton.dev/output_artifacts: '{"download": [{"key": "artifacts/$PIPELINERUN/download/downloaded.tgz",
      "name": "download-downloaded", "path": "/tmp/results.txt"}], "get-frequent":
      [{"key": "artifacts/$PIPELINERUN/get-frequent/word.tgz", "name": "get-frequent-word",
      "path": "/tmp/message.txt"}]}'
    tekton.dev/input_artifacts: '{"get-frequent": [{"name": "download-downloaded",
      "parent_task": "download"}], "save": [{"name": "get-frequent-word", "parent_task":
      "get-frequent"}]}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"download": [["downloaded", "$(results.downloaded.path)"]],
      "get-frequent": [["word", "$(results.word.path)"]], "save": []}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Download and Get Most
      Frequent Word and Save to GCS", "inputs": [{"default": "gs://ml-pipeline-playground/shakespeare1.txt",
      "name": "url", "optional": true, "type": "String"}, {"default": "res.txt", "name":
      "outputpath", "optional": true, "type": "String"}], "name": "Download and Save
      Most Frequent"}'
spec:
  params:
  - name: url
    value: gs://ml-pipeline-playground/shakespeare1.txt
  - name: outputpath
    value: res.txt
  pipelineSpec:
    params:
    - name: url
      default: gs://ml-pipeline-playground/shakespeare1.txt
    - name: outputpath
      default: res.txt
    tasks:
    - name: download
      params:
      - name: url
        value: $(params.url)
      taskSpec:
        steps:
        - name: main
          args:
          - gsutil cat $(inputs.params.url) | tee $(results.downloaded.path)
          command:
          - sh
          - -c
          image: google/cloud-sdk
        params:
        - name: url
        results:
        - name: downloaded
          description: /tmp/results.txt
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            tekton.dev/template: ''
      timeout: 0s
    - name: get-frequent
      params:
      - name: download-downloaded
        value: $(tasks.download.results.downloaded)
      taskSpec:
        steps:
        - name: main
          args:
          - echo '$(inputs.params.download-downloaded)' | tee /tmp/results.txt ; python
            -c "from collections import Counter; foo=open('"/tmp/results.txt"', 'r').read();words
            = Counter(foo.split()); print(max(words, key=words.get))" | tee $(results.word.path)
          command:
          - bash
          - -c
          image: python:3.5-jessie
        params:
        - name: download-downloaded
        results:
        - name: word
          description: /tmp/message.txt
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            tekton.dev/template: ''
      timeout: 0s
    - name: save
      params:
      - name: get-frequent-word
        value: $(tasks.get-frequent.results.word)
      - name: outputpath
        value: $(params.outputpath)
      taskSpec:
        steps:
        - name: main
          args:
          - echo '$(inputs.params.get-frequent-word)' | tee /tmp/results.txt | gsutil
            cp /tmp/results.txt '$(inputs.params.outputpath)'
          command:
          - sh
          - -c
          image: google/cloud-sdk
        params:
        - name: get-frequent-word
        - name: outputpath
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            tekton.dev/template: ''
      timeout: 0s
  timeout: 0s
